### PR TITLE
Add the suggest command user to the thread.

### PR DESCRIPTION
**Pull request by Zefyro**

### CODE REVIEW

**Comment by akiraveliara** [comment]
shouldn't this also be present in https://github.com/ExaInsanity/EagleThreadBot/blob/main/EagleThreadBot/SlashCommands/CreateCommand.cs#L32

**Comment by Zefyro** [comment]
true enough

**Comment by Zefyro** [comment]
there you go

**Review by akiraveliara — APPROVED** [review]

**Comment by akiraveliara** [comment]
will update the running version tomorrow

**Pull request merged**
